### ISSUE TITLE
"Missing transactionId"

### ISSUE THREAD

**Issue by sebbekarlsson** [codler/avanza-api#2]
I'm getting "Missing transactionId" in the catch function using this:

```javascript
avanza.authenticate({
     personnummer: personNumber
 }).then(isOk => {
     doSomething();
 }).catch((e) => { console.log(e) }); 
```

**Comment by codler** [comment]
It works for me, did you enter a valid personNumber , 12digits?

**Comment by sebbekarlsson** [comment]
@codler 
Yes I did use a valid personNumber, formated as "XXXXXX-XXXX"

I would also like to mention that I tried to use this within a react-native application for android
